version: '3.1'

services:
  server:
    image: node:10
    ports:
      - 3000:3000
    command: bash -c 'npm install && npm run debug'
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongo

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    logging:
      driver: 'none'

volumes:
  mongo-data:
